name: C/C++ CI

on: [push]

jobs:
  build:
    container:
      image: hoennecke/heaven:latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make -C code/heaven release
    - uses: actions/upload-artifact@v1
      with:
        name: tar-gz-build
        path: code/heaven/out/heaven.tar.gz
    - uses: actions/upload-artifact@v1
      with:
        name: zip-build
        path: code/heaven/out/heaven.zip
