name: C/C++ CI

on: [push]

jobs:
  build:
    container:
      image: hoennecke/heaven:latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make -C code/heaven release
